fix: UnlinkCategoryModal.vue(81,22): error TS2367: This comparison appears to be unintentional because the types '"de"' and '"en"' (#1189)
Co-authored-by: Tim Müller-Späth <11943448+Tim-M-S@users.noreply.github.com>
Co-authored-by: Tim Müller-Späth <tim.mueller.spaeth@gmail.com>